Traceback (most recent call last):
  File "main.py", line 7, in <module>
    import iv_check
  File "/home/daniel/PoGoPvPBot/iv_check.py", line 7, in <module>
    import database
  File "/home/daniel/PoGoPvPBot/database.py", line 7, in <module>
    import language_support
  File "/home/daniel/PoGoPvPBot/language_support.py", line 6, in <module>
    responses = json.load(json_config_file)
  File "/usr/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 123: invalid continuation byte
